{
 "title": "lambda-real-time-reporting",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "batch_layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anzahl Datensätze (kaggleImport)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kaggleimport_rows_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Verarbeitungsdauer (kaggleImport)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kaggleimport_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Anzahl Schedule durchläufe",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_runs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Anzahl Aggregationen (Tage)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_wrote_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "api_service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Gesamt-Anzahl API-Aufrufe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API-Aufrufe",
   "type": "timeseries",
   "description": "Anzahl der API-Aufrufe des api_service",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "api_requests_total", "legendFormat": "Anzahl" }
   ]
  },
  { "title": "speed_layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Anzahl Tumbling- Verarbeitungen",
   "type": "stat",
   "description": "Speed_Layer ausführungen (Tumbling)",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tumbling_windows_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Anzahl Tumbling - Events",
   "type": "stat",
   "description": "Durch Tumbling verarbeitete API-Events",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tumbling_events_processed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ingestion_layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Anzahl verarbeiteter API-Events",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_processed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Anzahl veröffentlichter API-Record",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "publish_records_total", "legendFormat": "__auto" }
   ]
  }
 ]
}