global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "api_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["api_service:8000"]

  - job_name: "ingestion_layer"
    static_configs:
      - targets: ["ingestion_layer:8001"]

  - job_name: "speed_layer"
    metrics_path: /metrics
    static_configs:
      - targets: ["speed_layer:7000"]

  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]