apiVersion: 1
datasources:
  - name: Prometheus
    uid: PROMDS
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
    jsonData:
      httpMethod: GET
      tlsSkipVerify: true